### ISSUE TITLE
trouble running

### ISSUE THREAD

**Issue by bioinfowheat** [markhilt/ARBitR#4]
Hello,

I can get your test dataset to run fine using
python3 ../src/arbitr.py -m 12000 -s 5000 -i ecoli.broken.fasta -o ecoli.test_data ecoli.broken.bam

but on my own data I get the following error. My bam was generated using bwa mem for mapping.

python3 /mnt/griffin/chrwhe/software/ARBitR/src/arbitr.py -m 45000 -s 5000 -i Polygonia-scaffolds.fa -o Pcalbum_10X Pcalbum_10X.sorted.bam 
[Sun Dec 13 21:09:47 2020]      Starting ARBitR.
[Sun Dec 13 21:09:48 2020]      Collecting contigs.
[Sun Dec 13 21:09:48 2020]      Collecting barcodes for linkgraph.
[Sun Dec 13 21:09:49 2020]      Starting barcode collection. Found 1016 contigs.
[Sun Dec 13 21:10:23 2020]      [ BARCODE COLLECTION ]  Completed: 100.0% (2032 out of 2032)
[Sun Dec 13 21:10:24 2020]      Creating link graph.
Traceback (most recent call last):
  File "/mnt/griffin/chrwhe/software/ARBitR/src/arbitr.py", line 250, in <module>
    main()
  File "/mnt/griffin/chrwhe/software/ARBitR/src/arbitr.py", line 194, in main
    barcode_fraction)
  File "/mnt/griffin/chrwhe/software/ARBitR/src/graph_building.py", line 507, in main
    GEMcomparison = pairwise_comparisons(GEMlist)
  File "/mnt/griffin/chrwhe/software/ARBitR/src/graph_building.py", line 390, in pairwise_comparisons
    misc.printstatus("[ BARCODE COMPARISON ]\t" + misc.reportProgress(idx+1, len(GEMlist)))
  File "/mnt/griffin/chrwhe/software/ARBitR/src/misc.py", line 29, in reportProgress
    return "Completed: {0}% ({1} out of {2})".format( str(round( (current / total) * 100, 2)), current, total)
ZeroDivisionError: division by zero

**Comment by markhilt** [comment]
Hi,

It seems ARBitR fails to find your contig starts and ends for comparing barcodes. ARBitR will skip any region that doesn't contain any useable barcodes. Did you run bwa with -C? If not, ARBitR won't find any barcodes at all which would trigger this error. If you did, what do your fasta headers look like?

Markus
